### PR TITLE
!!! Updated theme to current standards

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Close https://github.com/Codeinwp/bookrev-lite/issues/46

Many commits so please check commits for more info. @rodica-andronache

### CODE REVIEW

**Comment by ineagu** [comment]
@rodica-andronache since we did this, can we create a much better screenshot ? the current one is awful

**Comment by HardeepAsrani** [comment]
I will send one. :)

**Comment by rodica-andronache** [comment]
@HardeepAsrani thanks :) Will just have to change back the strings changed here https://github.com/Codeinwp/bookrev-lite/pull/47/commits/499f951a137ab990d7ef08253231167f4ce33186 to not change the translations percentage on wp.org as I mentioned on Bookrev.
Andrei will take care of the screenshot.

**Comment by HardeepAsrani** [comment]
@rodica-andronache I didn't change any strings, so can you screenshot it so I could see? Must be a mistake from my side.

Also just noticed this:

```wp_enqueue_style( '<font-></font->awesome', get_template_directory_uri() . '/css/font-awesome.min.css');```

My IDE turned `font` in `font awesome` to `<font> tag.

So let me know the string mistake so I could fix both. :)

**Comment by rodica-andronache** [comment]
I mean this http://pasteboard.co/ho9C3EggQ.png , when you changed ... to &hellip;  :D  but I already reversed here https://github.com/Codeinwp/bookrev-lite/commit/f072f5fb93d622114c6817e1ce04c552f2b6cac6 

You can still fix the fontawesome issue, I didn't notice it

**Comment by HardeepAsrani** [comment]
Oh, got it. Thanks.

**Pull request merged**
