### PR TITLE
Fixed the slider issue

### PR DESCRIPTION
**Pull request by HardeepAsrani**
If the post has Featured Image then display use it for the slider.

@ineagu I only changed two line and Github editor got mixed it up. You can use a different code comparison tool, hehe.

Fixes: https://github.com/Codeinwp/bookrev-lite/issues/23

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
The changed I made are from: 650-670 @ineagu

**Comment by ineagu** [comment]
@vncatalin is this ok for you ?

**Comment by vncatalin** [comment]
@ineagu I'll fix this today.

**Comment by ineagu** [comment]
@vncatalin in this case hardeep already sent a pull request, so you was required to approve it and merge, not redo it :)

**Pull request closed without merging**
